<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://services.main/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://services.main/" name="CheckRequestImplService">
    <message name="CheckRequest">
        <part name="parameters" element="tns:CheckRequest"/>
    </message>
    <message name="CheckRequestResponse">
        <part name="parameters" element="tns:CheckRequestResponse"/>
    </message>
    <portType name="CheckRequest">
        <operation name="CheckRequest">
            <input wsam:Action="http://services.main/CheckRequest/CheckRequestRequest" message="tns:CheckRequest"/>
            <output wsam:Action="http://services.main/CheckRequest/CheckRequestResponse" message="tns:CheckRequestResponse"/>
        </operation>
    </portType>
    <binding name="CheckRequestImplPortBinding" type="tns:CheckRequest">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="CheckRequest">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CheckRequestImplService">
        <port name="CheckRequestImplPort" binding="tns:CheckRequestImplPortBinding">
            <soap:address location="http://localhost:8081/ws/checkreq"/>
        </port>
    </service>
