<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://services.main/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://services.main/" name="ListDorayakiImplService">
    <message name="ListDorayakiPabrik">
        <part name="parameters" element="tns:ListDorayakiPabrik"/>
    </message>
    <message name="ListDorayakiPabrikResponse">
        <part name="parameters" element="tns:ListDorayakiPabrikResponse"/>
    </message>
    <portType name="ListDorayaki">
        <operation name="ListDorayakiPabrik">
            <input wsam:Action="http://services.main/ListDorayaki/ListDorayakiPabrikRequest" message="tns:ListDorayakiPabrik"/>
            <output wsam:Action="http://services.main/ListDorayaki/ListDorayakiPabrikResponse" message="tns:ListDorayakiPabrikResponse"/>
        </operation>
    </portType>
    <binding name="ListDorayakiImplPortBinding" type="tns:ListDorayaki">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="ListDorayakiPabrik">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="ListDorayakiImplService">
        <port name="ListDorayakiImplPort" binding="tns:ListDorayakiImplPortBinding">
            <soap:address location="http://localhost:8081/ws/list"/>
        </port>
    </service>
</definitions>